
mongodb:
  host: s100
  port: 27017
  user:
  passwd:
  database: sns

redis:
  host: s100
  port:
  user:
  passwd:

postgresql:
  dbname: swarm
  host: s203
  port: 5432
  user: postgres
  passwd: 111111


push_server:
  http:
    host:
    port: 16001
    ssl: false
    keyfile: /home/ssl/server.key
    certfile: /home/ssl/server.crt
  mongodb:  mongodb
  postgresql: postgresql
  redis: redis
  log:
    stdout: true
    file: ./pushserver.log
    dgram: localhost:9901
  app_bind_uri: http://s205:16003/WEBAPI/connector/app-account/event/bind
  job_server_data_analyses_uri: http://s189:16002/WEBAPI/jobserver/data/analyses

messageserver:
  mongodb:  mongodb
  postgresql: postgresql
  redis: redis
  log:
    stdout: true
    file: ./mexs.log
    dgram: localhost:9901


gwserver:
  mongodb:  mongodb
  postgresql: postgresql
  redis: redis
  log:
    stdout: true
    file: ./gwserver.log
    dgram: localhost:9901